export const avd_payload = {
  data: {
    cicle: {
      name: '00000000003 - Teste de relatório ',
      pattern: 'Avaliação customizada ',
      status: 'active',
      start_date: '26/10/2023 às 08:34',
      deadline: '09/11/2023 - 10/11/2023',
      scale_number: '5',
    },
    evaluated: {
      picture: null,
      initials: '0P',
      name: '02 TESTE JAIME VER PDI',
      position: '1/2 OFICIAL FERRAMENTEIRO',
      profiler: 'EP',
      department: 'AOs',
      employed_since: '0 ano e 7 meses',
      direct_leader: 'Felipe Neves',
    },
    moderator: {
      hasModerated: true,
      description:
        'Avaliação moderada em 09/11/2023 por Charles G Bragaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa100.',
    },
    average_ratings: {
      start_date: 'de 09/11/2023',
      end_date: 'a 10/11/2023',
      evaluated_average: '80.0%',
      position_average: '80.0%',
    },
    skill_ratings: {
      skill_group: [
        {
          id: 'skill-group-1',
          name: '0001e',
          average: 4,
        },
        {
          id: 'skill-group-2',
          name: '858738049_Teste_API',
          average: 4,
        },
        {
          id: 'skill-group-3',
          name: 'Competências Técnicas - Teste',
          average: 4,
        },
        {
          id: 'skill-group-4',
          name: 'Eixo COMPORTAMENTO',
          average: 4,
        },
        {
          id: 'skill-group-5',
          name: 'Eixo DESEMPENHO',
          average: 4,
        },
        {
          id: 'skill-group-6',
          name: 'TDEP-1656',
          average: 4,
        },
        {
          id: 'skill-group-7',
          name: 'Tipo de critério 01',
          average: 4,
        },
      ],
      skill: [
        {
          id: 'skill-group-1',
          rate_id: 'skill-1',
          name: '560059304349_criado pela automação de testes de APIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-1',
          rate_id: 'skill-2',
          name: 'aaaa',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-1',
          rate_id: 'skill-3',
          name: 'teste v3 2',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-2',
          rate_id: 'skill-4',
          name: 'teste arquivar jaime 08',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-5',
          name: 'Busca alternativas para situações difíceis',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Considere para avaliação:\n1 estrela = Demonstra dificuldade para apresentar soluções inovadoras\n2 estrelas = Eventualmente propõe soluções, mas necessita ser instigado para isso\n3 estrelas = Está em desenvolvimento e já consegue propor, de forma proativa, novas abordagens de atuação para algumas situações difíceis\n4 estrelas = Tem autonomia e usa a criatividade para simplificar problemas complexos\n5 estrelas = Apresenta ideias inovadoras com grande impacto para o negócio, resolve situações difíceis com muita facilidade',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-6',
          name: 'Competencia 01 vou dar um nome bem grande pra essa competência com o intuito de quebrar a linha para entender qual é o seu comportamento no relatório gerado em tela e no pdf também',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Este é um texto aleatório:\nEste é um texto aleatório:\nEste é um texto aleatório:\nEste é um texto aleatório:',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-7',
          name: 'Competencia 02',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Texto de teste\nTexto de teste\nTexto de teste\nTexto de teste\nTexto de teste',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-8',
          name: 'Competencia 05',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Texto de teste\nTexto de teste\nTexto de teste\nTexto de teste\nTexto de teste\nTexto de teste',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-9',
          name: 'Competencia 06',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-10',
          name: 'Competencia 07',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-11',
          name: 'Competencia 08',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-12',
          name: 'Competencia 09',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-13',
          name: 'Competencia 10',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-14',
          name: 'Teste de quebra de linha',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'To testando a quebra\nagora de novo\nagora varias vezes!\n\n\nFuncionou?',
        },
        {
          id: 'skill-group-3',
          rate_id: 'skill-15',
          name: 'TESTE JAIME COPETENCIA',
          evaluated_average: '80%',
          position_average: '80%',
          description: 'TESTE JAIME COPETENCIA',
        },
        {
          id: 'skill-group-4',
          rate_id: 'skill-16',
          name: '2 Competência COMPORTAMENTO',
          evaluated_average: '80%',
          position_average: '80%',
          description: '2 Competência COMPORTAMENTO descrição',
        },
        {
          id: 'skill-group-5',
          rate_id: 'skill-17',
          name: '1 Competência DESEMPENHO',
          evaluated_average: '80%',
          position_average: '80%',
          description: '1 Competência DESEMPENHO descrição',
        },
        {
          id: 'skill-group-5',
          rate_id: 'skill-18',
          name: '2 Competência DESEMPENHO',
          evaluated_average: '80%',
          position_average: '80%',
          description: '2 Competência DESEMPENHO descrição',
        },
        {
          id: 'skill-group-6',
          rate_id: 'skill-19',
          name: 'TDEP-1656',
          evaluated_average: '80%',
          position_average: '80%',
          description: '',
        },
        {
          id: 'skill-group-7',
          rate_id: 'skill-20',
          name: 'Jaime Teste novo',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Considere para avaliação:\n1 estrela = Demonstra dificuldade para apresentar solucdes inovadoras\n2 estrelas = Eventualmente propée solugdes, mas necessita ser instigado para isso\n3 estrelas = Esta em desenvolvimento e ja consegue propor, de forma proativa, novas abordagens de atuagéio para algumas situagées dificeis\n4 estrelas = Tem autonomia e usa a criatividade para simplificar problemas complexos\n5 estrelas = Apresenta ideias inovadoras com grande impacto para o negécio, resolve situacées dificeis com muita',
        },
        {
          id: 'skill-group-7',
          rate_id: 'skill-21',
          name: 'teste',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            'Considere para avaliação:\n1 estrela = Demonstra dificuldade para apresentar solucdes inovadoras\n2 estrelas = Eventualmente propée solugdes, mas necessita ser instigado para isso\n3 estrelas = Esta em desenvolvimento e ja consegue propor, de forma proativa, novas abordagens de atuagéio para algumas situagées dificeis\n4 estrelas = Tem autonomia e usa a criatividade para simplificar problemas complexos\n5 estrelas = Apresenta ideias inovadoras com grande impacto para o negécio, resolve situacées dificeis com muita',
        },
        {
          id: 'skill-group-7',
          rate_id: 'skill-22',
          name: 'Teste Selecionar todos',
          evaluated_average: '80%',
          position_average: '80%',
          description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        },
      ],
      rates: [
        {
          id: 'skill-1',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-1',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-1',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-1',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-2',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-2',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-2',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-2',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-3',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-3',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-3',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-3',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-4',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-4',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-4',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-4',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-5',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-5',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-5',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-5',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-6',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-6',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-6',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-6',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-7',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-7',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-7',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-7',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-8',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-8',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-8',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-8',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-9',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-9',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-9',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-9',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-10',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-10',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-10',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-10',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-11',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-11',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-11',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-11',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-12',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-12',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-12',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-12',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-13',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-13',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-13',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-13',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-14',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-14',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-14',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-14',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-15',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-15',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-15',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-15',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-16',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-16',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-16',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-16',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-17',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-17',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-17',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-17',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-18',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-18',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-18',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-18',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-19',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-19',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-19',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-19',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-20',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-20',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-20',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-20',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-21',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-21',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-21',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-21',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
        {
          id: 'skill-22',
          evaluator: 'Avaliador 1',
          width: '20%',
          bg: 'bg-purpura-500',
          rate: 1,
        },
        {
          id: 'skill-22',
          evaluator: 'Avaliador 2',
          width: '40%',
          bg: 'bg-purpura-400',
          rate: 2,
        },
        {
          id: 'skill-22',
          evaluator: 'Avaliador 3',
          width: '60%',
          bg: 'bg-purpura-300',
          rate: 3,
        },
        {
          id: 'skill-22',
          evaluator: 'Moderador 1',
          width: '80%',
          bg: 'bg-purpura-200',
          rate: 4,
        },
      ],
    },
    comments: [
      {
        evaluator: 'Avaliador 1',
        date: '09/11/2023',
        description: '<p>aaaaa</p>',
      },
      {
        evaluator: 'Avaliador 2',
        date: '09/11/2023',
        description: '<p>bbbbb</p>',
      },
      {
        evaluator: 'Avaliador 3',
        date: '09/11/2023',
        description: '<p>ccccc</p>',
      },
      {
        evaluator: 'Moderador 1',
        date: '09/11/2023',
        description: '<p>ddddd</p>',
      },
    ],
  },
  translate: {
    cicle: {
      status: 'Ativa',
      scale: 'Escala utilizada',
      created_at: 'Criada em',
      deadline: 'Prazo de participação',
    },
    evaluated: {
      department: 'Departamento',
      employed_since: 'Tempo de empresa',
      direct_leader: 'Superior direto',
    },
    average_ratings: {
      evaluation_deadline: 'Período de avaliação: ',
      collaborator_note_title: 'Nota do colaborador',
      collaborator_note_subtitle:
        'Nota geral utilizada no ranking dos colaboradores',
      position_note_title: 'Nota do cargo',
      position_note_subtitle: 'Nota média dos colaboradores',
    },
    skill_ratings: {
      title: 'Notas do colaborador',
      skill_group_subtitle: 'Nota média:',
      skill_subtitle: 'Notas por competência',
      position_subtitle: 'Média das pessoas de mesmo cargo',
      position_general_note: 'Nota geral',
      position_note_average: 'Média de notas do mesmo cargo',
    },
    comments: {
      title: 'Observações dos avaliadores',
    },
  },
};
