const profilerEn = {
  profile: 'EP',
  name: '02 TESTE JAIME VER PDI',
  email: 'marcia.sonia.peixoto@grupoblackout.com.br',
  language: 'en',
  type: 'simple',
  initialName: '0P',
  timeresult: '18 Seconds',
  date: 'June 5, 2023',
  answered: '05/06/2023',
  imageUser: '',
  charts: {
    labelsLevel: [
      {
        1: 'Extremely Low',
        2: 'Very low',
        3: 'Low',
        4: 'Low Normal',
        5: 'High normal',
        6: 'High',
        7: 'Very high',
        8: 'Extremely High',
      },
    ],
    profilerBar: {
      mainProfile: 'Executor Planner',
      profiles: [
        {
          label: 'executor',
          total: '29.93',
          level: 'High',
        },
        {
          label: 'communicator',
          total: '21.17',
          level: 'Low',
        },
        {
          label: 'analyst',
          total: '21.90',
          level: 'Low',
        },
        {
          label: 'planner',
          total: '27.01',
          level: 'High',
        },
      ],
    },
    factoryByProfiler: {
      analyst: [14.35406698564593, 0],
      communicator: [12.68292682926829, 2.7027027027027],
      executor: [14.97584541062802, 19.41747572815534],
      planner: [16.89497716894977, 0],
    },
    indicador: {
      customLabels: [
        'Low',
        'Low',
        'High normal',
        'Low',
        'Low Normal',
        'High normal',
        'Low Normal',
        'Very high',
        'High normal',
      ],
      values: [3, 3, 5, 3, 4, 5, 4, 7, 5],
      labels: [
        'Energy',
        'Environmental demands',
        'Utilization',
        'Morale',
        'Positivity',
        'Flexibility',
        'Scope',
        'Self-motivation',
        'Incitement',
      ],
    },
    competencies: {
      labels: [
        '1. Tolerance',
        '2. Planning',
        '3. Empathy',
        '4. Listening Skills',
        '5. Concentration',
        '6. Tolerance',
        '7. Technical Profile',
        '8. Organization',
        '9. Attention to Detail',
        '10. Rigor',
        '11. Results-Oriented',
        '12. Multitasking',
        '13. Self-Motivation',
        '14. Proactivity',
        '15. Dynamism',
        '16. Dominance',
        '17. Extroversion',
        '18. Interpersonal Relationship',
        '19. Sociability',
        '20. Relationship-Oriented',
      ],
      customLabels: [
        'High normal',
        'High',
        'High',
        'High',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High',
        'High',
        'High',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'High normal',
        'Low',
        'Low',
        'Low Normal',
        'Low Normal',
      ],
      guidelines: [
        '58.25',
        '69.43',
        '69.43',
        '69.43',
        '61.21',
        '61.21',
        '53.41',
        '53.41',
        '53.41',
        '61.55',
        '61.55',
        '69.28',
        '69.28',
        '69.28',
        '58.80',
        '58.80',
        '48.44',
        '48.44',
        '48.44',
        '58.25',
      ],
      skillLabelsValues: [
        5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
      ],
    },
    chartInterection: {
      requirement: [
        {
          name: 'Como a pessoa é',
          data: [4.93, -3.83, 2.01, -3.1],
        },
        {
          name: 'Como o ambiente cobra dela ser',
          data: [-1.62, 1.84, 1.41, -1.62],
        },
        {
          name: 'Ajuste a exigencia do ambiente',
          data: [-0.31, 0.71, 1.53, -1.92],
        },
      ],
      leadership: [
        {
          name: 'Como a pessoa é',
          data: [-0.95, -4.08, 0.95, 4.08],
        },
        {
          name: 'Como o ambiente cobra dela ser',
          data: [-1.82, 4.53, 1.82, -4.53],
        },
        {
          name: 'Ajuste a exigencia do ambiente',
          data: [-1.385, 2.808, 1.646, -0.225],
        },
      ],
    },
    talentsArea: {
      dx: '-2.19',
      dy: '-3.65',
      dx2: '-0.43',
      dy2: '6.49',
      indicators: {
        labels: [
          'Commander',
          'Competitor',
          'Administrator',
          'Motivator',
          'Seller',
          'Diplomat',
          'Advisor',
          'Attendant',
          'Professional',
          'Technician',
          'Specialist',
          'Strategist',
          'Controller',
        ],
      },
    },
  },
};
const profilerPt = {
  profile: 'PAC',
  name: 'Adriana Trindade Morato',
  email: 'adriana.trindade@montebravo.com.br',
  language: 'pt-br',
  type: 'simple',
  initialName: 'AM',
  timeresult: '12 Segundos',
  date: '29 de junho de 2022',
  answered: '29/06/2022',
  imageUser:
    'https://solides-gestao-stage.s3.amazonaws.com/colaborador/foto/413547/thumb_VOC_-_-DEMAIS1.png?X-Amz-Expires=21600&X-Amz-Date=20231106T135319Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAXDRBBSMYD7JWDONS%2F20231106%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=cb7ecbf7c29e2426123b90191d8802d1d8a6df2e3dab8f8305e8c8b6e2329b0b',
  charts: {
    labelsLevel: [
      {
        1: 'Extremamente Baixo',
        2: 'Muito Baixo',
        3: 'Baixo',
        4: 'Normal Baixo',
        5: 'Normal Alto',
        6: 'Alto',
        7: 'Muito Alto',
        8: 'Extremamente Alto',
      },
    ],
    profilerBar: {
      mainProfile: 'Planejador Analista Comunicador',
      profiles: [
        {
          label: 'executor',
          total: '12.66',
          level: 'Extremamente Baixo',
        },
        {
          label: 'comunicador',
          total: '26.58',
          level: 'Alto',
        },
        {
          label: 'analista',
          total: '29.11',
          level: 'Muito Alto',
        },
        {
          label: 'planejador',
          total: '31.65',
          level: 'Muito Alto',
        },
      ],
    },
    factoryByProfiler: {
      analyst: [4.78468899521531, 10.15625],
      communicator: [0.48780487804878, 18.01801801801802],
      executor: [0, 9.70873786407767],
      planner: [3.65296803652968, 17.89473684210526],
    },
    indicador: {
      customLabels: [
        'Baixo',
        'Normal Baixo',
        'Muito Baixo',
        'Normal Baixo',
        'Baixo',
        'Normal Baixo',
        'Normal Alto',
        'Normal Baixo',
        'Baixo',
      ],
      values: [3, 4, 2, 4, 3, 4, 5, 4, 3],
      labels: [
        'Energia',
        'Exigência do meio',
        'Aproveitamento',
        'Moral',
        'Positividade',
        'Flexibilidade',
        'Amplitude',
        'Automotivação',
        'Incitabilidade',
      ],
    },
    competencies: {
      labels: [
        '1. Tolerância',
        '2. Planejamento',
        '3. Empatia',
        '4. Capacidade de ouvir',
        '5. Concentração',
        '6. Condescendência',
        '7. Perfil Técnico',
        '8. Organização',
        '9. Detalhismo',
        '10. Rigorosidade',
        '11. Orientado por resultados',
        '12. Multitarefas',
        '13. Automotivação ',
        '14. Proatividade',
        '15. Dinamismo',
        '16. Dominância ',
        '17. Extroversão ',
        '18. Relacionamento interpessoal',
        '19. Sociabilidade ',
        '20. Orientado por relacionamento',
      ],
      customLabels: [
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Alto',
        'Normal Alto',
        'Normal Alto',
        'Normal Baixo',
        'Normal Baixo',
        'Normal Baixo',
        'Normal Baixo',
        'Normal Baixo',
        'Normal Alto',
        'Normal Alto',
        'Normal Alto',
        'Alto',
        'Normal Baixo',
        'Normal Baixo',
        'Baixo',
        'Normal Baixo',
      ],
      guidelines: [
        '70.41',
        '81.35',
        '81.35',
        '81.35',
        '76.04',
        '76.04',
        '71.01',
        '71.01',
        '71.01',
        '49.61',
        '49.61',
        '29.30',
        '29.30',
        '29.30',
        '45.16',
        '45.16',
        '60.83',
        '60.83',
        '60.83',
        '70.41',
      ],
      skillLabelsValues: [
        6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 4, 4, 4, 4, 4, 5, 5, 5, 6,
      ],
    },
    chartInterection: {
      requirement: [
        {
          name: 'Como a pessoa é',
          data: [-12.34, 1.58, 6.65, 4.11],
        },
        {
          name: 'Como o ambiente cobra dela ser',
          data: [-25, 6.11, 11.67, 7.22],
        },
        {
          name: 'Ajuste a exigencia do ambiente',
          data: [-22.47, 5.21, 10.66, 6.6],
        },
      ],
      leadership: [
        {
          name: 'Como a pessoa é',
          data: [-12.8, 13.005, 12.8, -13.005],
        },
        {
          name: 'Como o ambiente cobra dela ser',
          data: [-20, 29.24, 20.93, -20],
        },
        {
          name: 'Ajuste a exigencia do ambiente',
          data: [-16.4, 25.993, 19.304, -16.5025],
        },
      ],
    },
    talentsArea: {
      dx: '21.52',
      dy: '16.46',
      dx2: '37.78',
      dy2: '22.0',
      indicators: {
        labels: [
          'Comandante',
          'Competidor',
          'Administrador',
          'Motivador',
          'Vendedor',
          'Diplomata',
          'Aconselhador',
          'Atendente',
          'Professoral',
          'Técnico',
          'Especialista',
          'Estrategista',
          'Controlador',
        ],
      },
    },
  },
};

export default {
  en: { data: { ...profilerEn } },
  'pt-br': { data: { ...profilerPt } },
};
